### ISSUE TITLE
Whats the suggested architecture for having multiple cards of different types?

### ISSUE THREAD

**Issue by Esildor** [emtkd/Unity-SwipeableView#2]
I have a collection of ScriptableObjects that derive from a custom type (Card) 
ei:
```
class BattleCard : Card
class ProfileCard : Card
``` 
I then start my prototype (and this framework) by calling:
```
public class CardGenerater : Singleton<CardGenerater>
{
	public List<Card> DataSet;

	public CustomSwipeableView view;

	void OnEnable()
	{
		view.UpdateData(DataSet);
	}
}
```

which calls:
```
public class CustomSwipeableView : UISwipeableView<Card>
{
    public void UpdateData(List<Card> data)
    {
        base.Initialize(data);
    }
}
```
An important note here: CardGenerater.DataSet contains ScriptableObjects of type BattleCard and ProfileCard (and in the future, other types too)
This functions correctly and as expected, cards display and data gets assigned, however, I'd like to have **different prefabs for BattleCards and ProfileCards** (because they are functionally different)

Does this currently support this? If so, how should it be implemented?

**Comment by mtakada16** [comment]
Hi, @Esildor . Thanks for reporting the issue.

What does “different types” mean? That of "TData" in the UISwipeableView.cs？

Thanks.

**Comment by Esildor** [comment]
Hey @kiepng Thanks for the response! Sorry, my first description was half-ass at best. I've updated the original comment to be more descriptive.

**Comment by mtakada16** [comment]
Hi, @Esildor !
Sorry, this library doesn’t support different types of prefabs.
Can you incarnate “different functions” by giving each card a callback?

ex)
```
class Card
{
  public Action action;
}
```

```
class CustomCell : UISwipeableCell
{
  Button button;
  public override void UpdateContent(Card data)
  {
    button.onClick.AddListener(() => data.action?.Invoke());
  }
}
```

**Comment by Esildor** [comment]
Interesting.... And thanks for the reply!

I'll probably try tinkering with it. If I end up writing anything that's not too project specific, I'll submit a PR. Thanks for the need framework!
