### ISSUE TITLE
No WWW but sprites

### ISSUE THREAD

**Issue by craftercis** [emtkd/Unity-SwipeableView#3]
How can I make this without WWW? I use Sprites.

**Comment by Esildor** [comment]
I'd check out the readme again. It plainly shows how to do this:
```
public class UISwipeableCardDemo : UISwipeableCard<DemoCardData>
{
    [SerializeField] private Image bg;

    public override void UpdateContent(DemoCardData data)
    {
        bg.color = data.color;
    }
}
```

In your case you'd replace:
`bg.color = data.color;`
with:
`bg.sprite = data.YourCustomSprite;`

**Comment by mtakada16** [comment]
@Esildor Thanks for your comment!!

Hi, @craftercis .
Has your problem solved with Esildor's comment?

**Comment by craftercis** [comment]
> @Esildor Thanks for your comment!!
> 
> Hi, @craftercis .
> Has your problem solved with Esildor's comment?

Hey

Sorry for the late response. I found a workaround. But thanks a lot for your help!

Greetings,

Cis
